package com.qali.menu.scanner

import android.content.Context
import android.graphics.Bitmap
import android.util.Log
import com.google.ar.core.*
import com.qali.menu.ObjectDetectorHelper
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.util.concurrent.CompletableFuture

class Model3DScanner(private val context: Context) {
    
    companion object {
        private const val TAG = "Model3DScanner"
        private const val SCAN_QUALITY = 0.8f
        private const val MIN_SCAN_POINTS = 1000
    }
    
    private var arSession: ArSession? = null
    private var objectDetectorHelper: ObjectDetectorHelper? = null
    private var isScanning = false
    private var scanPoints = mutableListOf<Point>()
    private var currentObjectName: String? = null
    
    data class Point(
        val x: Float,
        val y: Float,
        val z: Float,
        val confidence: Float
    )
    
    data class ScanResult(
        val objectName: String,
        val modelPath: String,
        val thumbnailPath: String,
        val scanQuality: Float
    )
    
    interface ScanListener {
        fun onScanProgress(progress: Float)
        fun onScanComplete(result: ScanResult)
        fun onScanError(error: String)
    }
    
    fun initializeScanner(): Boolean {
        return try {
            arSession = ArSession(context)
            objectDetectorHelper = ObjectDetectorHelper(
                context = context,
                runningMode = ObjectDetectorHelper.RunningMode.LIVE_STREAM
            )
            true
        } catch (e: Exception) {
            Log.e(TAG, "Failed to initialize scanner", e)
            false
        }
    }
    
    suspend fun startScanning(objectName: String, listener: ScanListener): ScanResult = withContext(Dispatchers.IO) {
        try {
            currentObjectName = objectName
            isScanning = true
            scanPoints.clear()
            
            // Start AR session
            arSession?.let { session ->
                val config = Config(session)
                config.updateMode = Config.UpdateMode.LATEST_CAMERA_IMAGE
                config.focusMode = Config.FocusMode.AUTO
                session.configure(config)
                session.resume()
            }
            
            // Scan from multiple angles
            val angles = listOf(0f, 45f, 90f, 135f, 180f, 225f, 270f, 315f)
            var progress = 0f
            
            for (angle in angles) {
                if (!isScanning) break
                
                // Capture frame at this angle
                val frame = arSession?.update()
                frame?.let { captureFrame(it, angle) }
                
                progress += 1f / angles.size
                listener.onScanProgress(progress)
                
                // Wait for next frame
                Thread.sleep(500)
            }
            
            // Generate 3D model
            val modelPath = generate3DModel(objectName)
            val thumbnailPath = generateThumbnail(objectName)
            
            val result = ScanResult(
                objectName = objectName,
                modelPath = modelPath,
                thumbnailPath = thumbnailPath,
                scanQuality = calculateScanQuality()
            )
            
            listener.onScanComplete(result)
            result
            
        } catch (e: Exception) {
            Log.e(TAG, "Scanning failed", e)
            listener.onScanError(e.message ?: "Unknown error")
            throw e
        } finally {
            stopScanning()
        }
    }
    
    private fun captureFrame(frame: Frame, angle: Float) {
        val camera = frame.camera
        val pose = camera.pose
        
        // Get point cloud
        val pointCloud = frame.acquirePointCloud()
        val points = pointCloud.points
        
        for (i in 0 until points.remaining()) {
            val point = points.get()
            val confidence = pointCloud.confidences?.get(i) ?: 0f
            
            if (confidence > SCAN_QUALITY) {
                scanPoints.add(Point(point.x, point.y, point.z, confidence))
            }
        }
        
        pointCloud.release()
    }
    
    private fun generate3DModel(objectName: String): String {
        val modelDir = File(context.filesDir, "models")
        modelDir.mkdirs()
        
        val modelFile = File(modelDir, "${objectName}_model.obj")
        
        // Generate OBJ file from scan points
        val objContent = buildString {
            appendLine("# 3D Model generated for $objectName")
            appendLine("# Generated by Menu App")
            appendLine()
            
            // Vertices
            scanPoints.forEach { point ->
                appendLine("v ${point.x} ${point.y} ${point.z}")
            }
            
            // Generate faces (simplified triangulation)
            for (i in 0 until scanPoints.size - 2 step 3) {
                appendLine("f ${i + 1} ${i + 2} ${i + 3}")
            }
        }
        
        modelFile.writeText(objContent)
        return modelFile.absolutePath
    }
    
    private fun generateThumbnail(objectName: String): String {
        val thumbnailDir = File(context.filesDir, "thumbnails")
        thumbnailDir.mkdirs()
        
        val thumbnailFile = File(thumbnailDir, "${objectName}_thumb.jpg")
        
        // Create a simple thumbnail (in a real app, this would be a rendered view)
        val bitmap = Bitmap.createBitmap(200, 200, Bitmap.Config.ARGB_8888)
        val canvas = android.graphics.Canvas(bitmap)
        val paint = android.graphics.Paint().apply {
            color = android.graphics.Color.GRAY
            style = android.graphics.Paint.Style.FILL
        }
        canvas.drawRect(0f, 0f, 200f, 200f, paint)
        
        val outputStream = FileOutputStream(thumbnailFile)
        bitmap.compress(Bitmap.CompressFormat.JPEG, 90, outputStream)
        outputStream.close()
        
        return thumbnailFile.absolutePath
    }
    
    private fun calculateScanQuality(): Float {
        return if (scanPoints.size >= MIN_SCAN_POINTS) {
            val avgConfidence = scanPoints.map { it.confidence }.average().toFloat()
            (avgConfidence * 0.7f + (scanPoints.size.toFloat() / MIN_SCAN_POINTS) * 0.3f).coerceIn(0f, 1f)
        } else {
            0f
        }
    }
    
    fun stopScanning() {
        isScanning = false
        arSession?.pause()
    }
    
    fun release() {
        stopScanning()
        arSession?.close()
        objectDetectorHelper?.clearObjectDetector()
    }
}